# API
API_SSH_HOST="10.108.1.10"
API_SSH_PORT="22"
API_SSH_USER="nlroot"

# DB
DB_SSH_HOST="10.108.1.11"
DB_SSH_PORT="22"
DB_SSH_USER="nlroot"

# Reverse API
REVERSE_API_SSH_HOST="10.108.1.12"
REVERSE_API_SSH_PORT="22"
REVERSE_API_SSH_USER="nlroot"

#WEB
WEB_SSH_HOST=""
WEB_SSH_PORT=22
WEB_SSH_USER="install"

#REVERSE PROXY WEB
REVERSE_WEB_SSH_HOST=""
REVERSE_WEB_SSH_PORT=22
REVERSE_WEB_SSH_USER="install"

#NODE EXPORTER
NODE_EXPORTER_SSH_HOST=""
NODE_EXPORTER_SSH_PORT=22
NODE_EXPORTER_SSH_USER="install"

#NODE EXPORTER DB
NODE_EXPORTER_DB_SSH_HOST=""
NODE_EXPORTER_DB_SSH_PORT=22
NODE_EXPORTER_DB_SSH_USER="install"

#MONITORING
MONITORING_SSH_HOST=""
MONITORING_SSH_PORT=22
MONITORING_SSH_USER="install"
